/* 预设供应商目录(2026-08-16 定稿 27 家+2xapi 置顶;logo=图标库品牌原文;协议由网关自动转译) */
window.PRESETS = [
  {id:"2xapi",name:"2xapi(官方)",logo:"assets/logos/2xapi.svg",iconColor:"#3D7EFF",baseUrl:"https://2xapi.cc.cd",proto:"chat",top:true},
  {id:"openai",name:"OpenAI",logo:"assets/logos/openai.svg",iconColor:"#10A37F",baseUrl:"https://api.openai.com/v1",proto:"responses",top:false},
  {id:"anthropic",name:"Anthropic (Claude)",logo:"assets/logos/anthropic.svg",iconColor:"#CC785C",baseUrl:"https://api.anthropic.com/v1",proto:"anthropic",top:false},
  {id:"gemini",name:"Google (Gemini)",logo:"assets/logos/gemini.svg",iconColor:"#4285F4",baseUrl:"https://generativelanguage.googleapis.com",proto:"gemini",top:false},
  {id:"xai",name:"xAI (Grok)",logo:"assets/logos/xai.svg",iconColor:"#000000",baseUrl:"https://api.x.ai/v1",proto:"chat",top:false},
  {id:"meta",name:"Meta (Llama)",logo:"assets/logos/meta.svg",iconColor:"#0866FF",baseUrl:"https://api.llama.com/compat/v1",proto:"chat",top:false},
  {id:"mistral",name:"Mistral AI",logo:"assets/logos/mistral.svg",iconColor:"#FF7000",baseUrl:"https://api.mistral.ai/v1",proto:"chat",top:false},
  {id:"cohere",name:"Cohere",logo:"assets/logos/cohere.svg",iconColor:"#39594D",baseUrl:"https://api.cohere.com/compatibility/v1",proto:"chat",top:false},
  {id:"perplexity",name:"Perplexity",logo:"assets/logos/perplexity.svg",iconColor:"#20808D",baseUrl:"https://api.perplexity.ai",proto:"chat",top:false},
  {id:"deepseek",name:"DeepSeek",logo:"assets/logos/deepseek.svg",iconColor:"#4D6BFE",baseUrl:"https://api.deepseek.com/v1",proto:"chat",top:false},
  {id:"kimi",name:"月之暗面 Kimi(含 Coding Plan)",logo:"assets/logos/kimi.svg",iconColor:"#000000",baseUrl:"https://api.moonshot.cn/v1",proto:"chat",top:false},
  {id:"zhipu",name:"智谱 GLM",logo:"assets/logos/zhipu.svg",iconColor:"#3657ED",baseUrl:"https://open.bigmodel.cn/api/paas/v4",proto:"chat",top:false},
  {id:"minimax",name:"MiniMax(含 Token Plan)",logo:"assets/logos/minimax.svg",iconColor:"#615CED",baseUrl:"https://api.minimaxi.com/v1",proto:"chat",top:false},
  {id:"xiaomimimo",name:"小米 MiMo(含 Token Plan)",logo:"assets/logos/xiaomimimo.svg",iconColor:"#FF6900",baseUrl:"https://api.xiaomimimo.com/v1",proto:"chat",top:false},
  {id:"qwen",name:"阿里通义 Qwen(百炼)",logo:"assets/logos/qwen.svg",iconColor:"#FF6A00",baseUrl:"https://dashscope.aliyuncs.com/compatible-mode/v1",proto:"chat",top:false},
  {id:"doubao",name:"字节豆包(火山方舟)",logo:"assets/logos/doubao.svg",iconColor:"#00C8C8",baseUrl:"https://ark.cn-beijing.volces.com/api/v3",proto:"chat",top:false},
  {id:"baidu",name:"百度文心(千帆)",logo:"assets/logos/baidu.svg",iconColor:"#2932E1",baseUrl:"https://qianfan.baidubce.com/v2",proto:"chat",top:false},
  {id:"hunyuan",name:"腾讯混元",logo:"assets/logos/hunyuan.svg",iconColor:"#00A3FF",baseUrl:"https://api.hunyuan.cloud.tencent.com/v1",proto:"chat",top:false},
  {id:"baichuan",name:"百川智能",logo:"assets/logos/baichuan.svg",iconColor:"#0066FF",baseUrl:"https://api.baichuan-ai.com/v1",proto:"chat",top:false},
  {id:"stepfun",name:"阶跃星辰 StepFun",logo:"assets/logos/stepfun.svg",iconColor:"#7C4DFF",baseUrl:"https://api.stepfun.com/v1",proto:"chat",top:false},
  {id:"spark",name:"讯飞星火",logo:"assets/logos/spark.svg",iconColor:"#E60012",baseUrl:"https://spark-api-open.xf-yun.com/v1",proto:"chat",top:false},
  {id:"yi",name:"零一万物 01.AI",logo:"assets/logos/yi.svg",iconColor:"#003425",baseUrl:"https://api.lingyiwanwu.com/v1",proto:"chat",top:false},
  {id:"nvidia",name:"NVIDIA NIM",logo:"assets/logos/nvidia.svg",iconColor:"#76B900",baseUrl:"https://integrate.api.nvidia.com/v1",proto:"chat",top:false},
  {id:"azure",name:"Azure OpenAI",logo:"assets/logos/azure.svg",iconColor:"#0078D4",baseUrl:"",proto:"chat",top:false},
  {id:"groq",name:"Groq",logo:"assets/logos/groq.svg",iconColor:"#F55036",baseUrl:"https://api.groq.com/openai/v1",proto:"chat",top:false},
  {id:"siliconflow",name:"SiliconFlow 硅基流动",logo:"assets/logos/siliconflow.svg",iconColor:"#7C3AED",baseUrl:"https://api.siliconflow.cn/v1",proto:"chat",top:false},
  {id:"ollama",name:"Ollama(本地)",logo:"assets/logos/ollama.svg",iconColor:"#FFFFFF",baseUrl:"http://127.0.0.1:11434/v1",proto:"chat",top:false},
  {id:"lmstudio",name:"LM Studio(本地)",logo:"assets/logos/lmstudio.svg",iconColor:"#4A90D9",baseUrl:"http://127.0.0.1:1234/v1",proto:"chat",top:false}
];
